version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: 'under10s-production'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3307:3306"
    networks:
      - my-network

  service-registry:
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - my-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/basics?allowPublicKeyRetrieval=true
      - eureka.instance.client.serverUrl.defaultZone = http://service-registry:8761/eureka/
      - spring.datasource.username=admin
      - spring.datasource.password=admin
    depends_on:
      - mysql-db
    networks:
      - my-network
    links:
      - service-registry

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql-db
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/basics?allowPublicKeyRetrieval=true
      - spring.datasource.username=admin
      - spring.datasource.password=admin
      - eureka.instance.client.serverUrl.defaultZone = http://service-registry:8761/eureka/
    networks:
      - my-network
    links:
      - service-registry

networks:
  my-network:
